abstract: ''
author: Six Apart <cpan@sixapart.com>
distribution_type: module
generated_by: Module::Install version 0.57
license: perl
name: Data-ObjectDriver
no_index:
  directory:
    - t
    - inc
    - t
requires:
  Class::Accessor::Fast: 0
  Class::Data::Inheritable: 0
  Class::Trigger: 0
  DBI: 0
version: 0.02
