--- 
abstract: ''
author: 
  - Six Apart <cpan@sixapart.com>
build_requires: 
  Test::Exception: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Data-ObjectDriver
no_index: 
  directory: 
    - t
    - inc
    - t
recommends: 
  Text::SimpleTable: 0
requires: 
  Class::Accessor::Fast: 0
  Class::Data::Inheritable: 0
  Class::Trigger: 0
  DBI: 0
  List::Util: 0
version: 0.06
